"""
app/bob/models.py
==================
Pydantic models for the IBM Bob integration layer.

DESIGN RATIONALE
----------------
These models form the versioned API surface between Worky and IBM Bob:

  BobRequest
      The payload sent to IBM Bob.  Wraps a WorkContext in the envelope
      shape the Bob API expects.

  Recommendation
      A single prioritised action item returned by IBM Bob.

  RecommendationSet
      The complete set of recommendations for one user at one point in time.
      This is what BobService.analyze() always returns.

Bob receives a WorkContext.  Bob returns a RecommendationSet.
No other format is permitted on either side of this boundary (ADR-006).

IMPORT RULES
------------
This module may import from:
  • Python standard library
  • Pydantic
  • app.context_builder.models  (WorkContext — Bob's only input type)

It must NOT import from:
  • app.connectors.*           (Bob must not know about connector schemas)
  • app.auth
  • app.config
  • app.recommendations        (that is the next layer up)
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

from app.context_builder.models import WorkContext


# ---------------------------------------------------------------------------
# Request model
# ---------------------------------------------------------------------------

class BobRequest(BaseModel):
    """
    The payload envelope sent to the IBM Bob reasoning API.

    BobService serialises this via model_dump() and POSTs the result to
    Bob's endpoint.  The top-level ``context`` field contains the full
    WorkContext so Bob has everything it needs in a single, versioned payload.

    Fields
    ------
    context : WorkContext
        The complete, point-in-time snapshot of the user's work environment
        assembled by the ContextBuilder.  This is the ONLY data Bob receives —
        it never receives raw connector data or individual connector responses.

    request_id : str
        A unique identifier for this analysis request.  Used for correlating
        Bob API requests with log entries and cached results.  Populated by
        BobService before sending.

    requested_at : datetime
        UTC timestamp of when this request was created.  Bob may use this to
        understand how recently the data was collected relative to now.
    """

    context: WorkContext = Field(
        ...,
        description="The full work context assembled by ContextBuilder.",
    )

    request_id: str = Field(
        ...,
        description="Unique identifier for this Bob analysis request.",
    )

    requested_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when this request was created.",
    )

    model_config = {"frozen": False}


# ---------------------------------------------------------------------------
# Recommendation (single item)
# ---------------------------------------------------------------------------

class Recommendation(BaseModel):
    """
    A single prioritised action item generated by IBM Bob.

    This model mirrors the individual item shape defined in
    ARCHITECTURE.md Section 10 (Widget Communication).  The
    RecommendationService layer will later wrap a list of these
    inside RecommendationResponse for the widget.

    Fields
    ------
    priority : int
        Ordering rank assigned by Bob.  1 is the highest priority.
        Bob determines this based on urgency, importance, and deadlines.

    category : str
        The domain this recommendation belongs to.  Examples:
          "email"     — an email requiring attention
          "meeting"   — an upcoming or missed meeting
          "message"   — a Slack or Teams message requiring response
          "task"      — an open PR or Jira ticket
          "general"   — a cross-cutting recommendation

    title : str
        A short, action-oriented headline.  Displayed as the primary text
        in the widget recommendation item.  Should be under 80 characters.

    description : str
        A one-to-two sentence explanation of why this item is prioritised
        and what the user should do.  Displayed as the secondary text.

    action_url : str
        Deep-link URL to the source item (e.g., the email in Outlook Web,
        the PR on GitHub, the meeting in Teams).  Empty string when no
        specific URL is available.

    source : str
        The connector source that contributed the underlying data.  Examples:
          "outlook", "slack", "github".
        Used by the widget to display a source icon or label.
    """

    priority: int = Field(
        ...,
        ge=1,
        description="Ordering rank.  1 = highest priority.",
    )

    category: str = Field(
        ...,
        description=(
            "Domain category: 'email', 'meeting', 'message', 'task', 'general'."
        ),
    )

    title: str = Field(
        ...,
        description="Short, action-oriented headline (≤80 characters).",
    )

    description: str = Field(
        ...,
        description="One-to-two sentence explanation of why this item is prioritised.",
    )

    action_url: str = Field(
        default="",
        description="Deep-link URL to the source item.  Empty string when unavailable.",
    )

    source: str = Field(
        ...,
        description="Connector source name that contributed the underlying data.",
    )

    model_config = {
        "frozen": False,
        # model_version starts with "model_" which Pydantic protects by default.
        # We own this field name intentionally — suppress the namespace warning.
        "protected_namespaces": (),
    }


# ---------------------------------------------------------------------------
# RecommendationSet (Bob's complete output for one user / one cycle)
# ---------------------------------------------------------------------------

class RecommendationSet(BaseModel):
    """
    The complete output of one IBM Bob analysis cycle.

    BobService.analyze() always returns exactly one RecommendationSet.
    The Recommendation Service (Phase 11) stores this in the cache keyed
    by user_id and serves it to the widget via GET /api/v1/recommendations.

    Fields
    ------
    user_id : str
        The Worky-internal user identifier for whom these recommendations
        were generated.  Passed through from the input WorkContext.

    generated_at : datetime
        UTC timestamp of when Bob completed this analysis.  The widget
        uses this (via the Recommendation Service) to display the
        ``context_freshness`` field.

    recommendations : list[Recommendation]
        The prioritised list of action items, ordered by priority ascending
        (priority 1 first).  Bob determines the count and ordering.

    model_version : str
        Version identifier for the Bob model or prompt that generated these
        recommendations.  Used for observability and debugging.  "mock" for
        MockBobService output.

    metadata : dict[str, Any]
        Operational metadata attached by BobService.  Not consumed by the
        widget.  Examples:
          {"latency_ms": 1240, "active_sources": ["outlook", "slack"]}
    """

    user_id: str = Field(
        ...,
        description="Worky-internal user identifier.",
    )

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when Bob completed this analysis.",
    )

    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="Prioritised action items, ordered by priority ascending.",
    )

    model_version: str = Field(
        default="unknown",
        description="Bob model/prompt version that produced these recommendations.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Operational metadata.  Not consumed by the widget.",
    )

    model_config = {
        "frozen": False,
        # model_version starts with "model_" which Pydantic protects by default.
        # We own this field name intentionally — suppress the namespace warning.
        "protected_namespaces": (),
    }
